sequenceDiagram
    participant DEP as Device Enrollment Program
    participant WSO as Workspace ONE UEM
    participant JC as JumpCloud

    DEP->>WSO: Workspace One UEM configured as MDM Server in DEP
    WSO->>DEP: DEP configured within Workspace One UEM
    DEP-->>WSO: MacOS devices assigned to Workspace One UEM MDM server in DEP
    JC->>JC: LDAP configured in JumpCloud
    WSO-->>JC: JumpCloud LDAP configured in "Enterprise Integration" > "Directory Services" Settings
    WSO->>WSO: DEP profile configured in Workspace One UEM
    WSO-->>WSO: DEP profile "Authentication" option enabled
    DEP->>JC: Enabling "Authentication" turns on JumpCloud LDAP authenticate for users during "Setup Assistant"
    WSO-->>DEP: "Enrollment Status" device list shows MacOS devices assigned in DEP
    WSO->>WSO: "Provisioning" > "Product" configured in Workspace One UEM and scoped to DEP enrolled  devices
    WSO-->>JC: "Files/Actions" component for JumpCloud agent installation configured
    WSO-->>JC: "Files/Actions" component for auto-association of logged in user to system in JumpCloud configured
    WSO-->>JC: "Files/Actions" component for JumpCloud local account takeover configured
   Note over DEP, JC:MacOS devices assigned to MDM server configured for zero-touch provisioning