$userParams = @{
    Property =
    @{Name = "firstname"; Expression = { $_.firstname } },
    @{Name = "lastname"; Expression = { $_.lastname } },
    @{Name = "username"; Expression = { $_.username } },
    @{Name = "email"; Expression = { $_.email } },
    @{Name = "password_never_expires"; Expression = { $_.password_never_expires } },
    @{Name = "allow_public_key"; Expression = { $_.allow_public_key } },
    @{Name = "sudo"; Expression = { $_.sudo } },
    @{Name = "enable_managed_uid"; Expression = { $_.enable_managed_uid } },
    @{Name = "unix_uid"; Expression = { $_.unix_uid } },
    @{Name = "unix_guid"; Expression = { $_.unix_guid } },
    @{Name = "passwordless_sudo"; Expression = { $_.passwordless_sudo } },
    @{Name = "ldap_binding_user"; Expression = { $_.ldap_binding_user } },
    @{Name = "enable_user_portal_multifactor"; Expression = { $_.enable_user_portal_multifactor } },
    @{Name = "middlename"; Expression = { $_.middlename } },
    @{Name = "displayname"; Expression = { $_.displayname } },
    @{Name = "jobTitle"; Expression = { $_.jobTitle } },
    @{Name = "employeeIdentifier"; Expression = { $_.employeeIdentifier } },
    @{Name = "department"; Expression = { $_.department } },
    @{Name = "costCenter"; Expression = { $_.costCenter } },
    @{Name = "company"; Expression = { $_.company } },
    @{Name = "employeeType"; Expression = { $_.employeeType } },
    @{Name = "description"; Expression = { $_.description } },
    @{Name = "location"; Expression = { $_.location } },
    @{Name = "work_streetAddress"; Expression = { $_.addresses | ? type -EQ work | Select-Object -ExpandProperty streetAddress } },
    @{Name = "work_poBox"; Expression = { $_.addresses | ? type -EQ work | Select-Object -ExpandProperty poBox } },
    @{Name = "work_locality"; Expression = { $_.addresses | ? type -EQ work | Select-Object -ExpandProperty locality } },
    @{Name = "work_region"; Expression = { $_.addresses | ? type -EQ work | Select-Object -ExpandProperty region } },
    @{Name = "work_postalCode"; Expression = { $_.addresses | ? type -EQ work | Select-Object -ExpandProperty postalCode } },
    @{Name = "work_country"; Expression = { $_.addresses | ? type -EQ work | Select-Object -ExpandProperty country } },
    @{Name = "home_streetAddress"; Expression = { $_.addresses | ? type -EQ home | Select-Object -ExpandProperty streetAddress } },
    @{Name = "home_poBox"; Expression = { $_.addresses | ? type -EQ home | Select-Object -ExpandProperty poBox } },
    @{Name = "home_locality"; Expression = { $_.addresses | ? type -EQ home | Select-Object -ExpandProperty locality } },
    @{Name = "home_region"; Expression = { $_.addresses | ? type -EQ home | Select-Object -ExpandProperty region } },
    @{Name = "home_postalCode"; Expression = { $_.addresses | ? type -EQ home | Select-Object -ExpandProperty  postalCode } },
    @{Name = "home_country"; Expression = { $_.addresses | ? type -EQ home | Select-Object -ExpandProperty country } },
    @{Name = "mobile_number"; Expression = { $_.phoneNumbers | ? type -EQ mobile | Select-Object -ExpandProperty number } },
    @{Name = "home_number"; Expression = { $_.phoneNumbers | ? type -EQ home | Select-Object -ExpandProperty number } },
    @{Name = "work_number"; Expression = { $_.phoneNumbers | ? type -EQ work | Select-Object -ExpandProperty number } },
    @{Name = "work_mobile_number"; Expression = { $_.phoneNumbers | ? type -EQ work_mobile | Select-Object -ExpandProperty number } },
    @{Name = "work_fax_number"; Expression = { $_.phoneNumbers | ? type -EQ work_fax | Select-Object -ExpandProperty number } },
    @{Name = "mfaConfigured"; Expression = { $_.mfa.configured } }

}


Get-JCUser | Select-Object @userParams | Export-CSV -Path "JumpCloudUsers_$(Get-Date -Format MMddyyyy).CSV" -NoTypeInformation -Force