Describe 'Generate User Cert Tests' -Tag "Generate" {
    Context 'Certs forcibly re-generated for all users' {
        It 'Certs re-generated have actually been re-written for all users' {
            . "/Users/jworkman/Documents/GitHub/support/scripts/automation/Radius/Functions/Public/Distribute-UserCerts.ps1"
            $timeBefore = (Get-Date).ToString('MM/dd/yyyy HH:mm:ss')
            $certsBefore = Get-CertInfo -UserCerts
            # wait one second.
            Start-Sleep 1
            Generate-UserCerts -type All -forceReplaceCerts
            # validate that the commands were created for valid users
            # Get Certs
            $certs = Get-CertInfo -UserCerts
            foreach ($cert in $certs) {
                $matchingBeforeCert = $certsBefore | Where-Object { $username -eq $cert.username }
                # Each cert should have a generated date -gt the $timeBefore
                $cert.generated | should -BeGreaterThan $timeBefore
                $cert.generated | should -BeGreaterThan $matchingBeforeCert.generated
                $cert.serial | should -Not -Be $matchingBeforeCert.serial
                $cert.sha1 | should -Not -Be $matchingBeforeCert.sha1
            }
        }
    }
    Context 'Certs generated for newly added users' {

    }
    Context 'Certs generated for users whos cert is set to exipre soon' {

    }
    Context 'Certs generated by username' {

    }
}