Describe -Tag('JCWorkflow') 'Get-JCWorkflow 1.0' {
    BeforeAll {
    Import-Module "$PSScriptRoot/../../../JumpCloud.psd1" -Force

    # Ensure connection is initialized
    if ([string]::IsNullOrEmpty($global:JCAPIKEY) -and [string]::IsNullOrEmpty($env:JCAPIKEY)) {
        [void](Connect-JCOnline)
    } else {
        [void](Connect-JCOnline -JumpCloudAPIKey ($global:JCAPIKEY ?? $env:JCAPIKEY) -Force)
    }

    # Safely retrieve Role ID for execution
    $script:roleId = InModuleScope 'JumpCloud' {
        $roles = Invoke-JCApi -Method GET -Url "$JCUrlBasePath/api/v2/roles"
        if ($roles.results -and $roles.results.Count -gt 0) {
            return $roles.results[0].id
        } elseif ($roles -and $roles.Count -gt 0) {
            return $roles[0].id
        }
        return $null
    }

    # Valid DSL structure generated by official JumpCloud Gemini Gem
    $script:dsl = @{
        schedule = @{
            on = @{
                one = @{
                    with = @{
                        source = "external"
                    }
                }
            }
        }
        do = @(
            @{
                getSystemUsers = @{
                    call = "jc_operation"
                    with = @{
                        operationId = "getApiSystemusers"
                        queryParams = @{
                            limit = 10
                        }
                    }
                }
            }
        )
    }
    $script:testName = "Pester_Get_$(Get-Random)"

    if ($script:roleId) {
        $script:testWorkflow = New-JCWorkflow -Name $script:testName -ExecutionRoleId $script:roleId -Dsl $script:dsl
    }
}

    AfterAll {
        if ($script:testWorkflow.id) {
            $workflowId = $script:testWorkflow.id
            try {
                InModuleScope 'JumpCloud' {
                    Invoke-JCApi -Method DELETE -Url "$JCUrlBasePath/api/v2/workflows/$workflowId"
                }
            } catch {
                # Ignore cleanup errors if endpoint behaves differently or resource is already purged
            }
        }
    }

    It "Gets all JumpCloud workflows" {
        $allWorkflows = Get-JCWorkflow
        $allWorkflows.Count | Should -BeGreaterThan 0
    }

    It "Gets a single JumpCloud workflow declaring -Id" {
        $singleResult = Get-JCWorkflow -Id $script:testWorkflow.id
        $singleResult.id | Should -Be $script:testWorkflow.id
    }

    It "Gets a single JumpCloud workflow searching by -Name" {
        $singleResult = Get-JCWorkflow -Name $script:testName
        $singleResult.name | Should -Be $script:testName
    }
}