Describe -Tag('JCWorkflow') 'New-JCWorkflow 1.0' {
    BeforeAll {
    Import-Module "$PSScriptRoot/../../../JumpCloud.psd1" -Force

    # Ensure connection is initialized
    if ([string]::IsNullOrEmpty($global:JCAPIKEY) -and [string]::IsNullOrEmpty($env:JCAPIKEY)) {
        [void](Connect-JCOnline)
    } else {
        [void](Connect-JCOnline -JumpCloudAPIKey ($global:JCAPIKEY ?? $env:JCAPIKEY) -Force)
    }

    # Safely retrieve Role ID for execution
    $script:roleId = InModuleScope 'JumpCloud' {
        $roles = Invoke-JCApi -Method GET -Url "$JCUrlBasePath/api/v2/roles"
        if ($roles.results -and $roles.results.Count -gt 0) {
            return $roles.results[0].id
        } elseif ($roles -and $roles.Count -gt 0) {
            return $roles[0].id
        }
        return $null
    }

    # Valid DSL structure generated by official JumpCloud Gemini Gem
    $script:dsl = @{
        schedule = @{
            on = @{
                one = @{
                    with = @{
                        source = "external"
                    }
                }
            }
        }
        do = @(
            @{
                getSystemUsers = @{
                    call = "jc_operation"
                    with = @{
                        operationId = "getApiSystemusers"
                        queryParams = @{
                            limit = 10
                        }
                    }
                }
            }
        )
    }
    $script:testName = "Pester_Get_$(Get-Random)"

    if ($script:roleId) {
        $script:testWorkflow = New-JCWorkflow -Name $script:testName -ExecutionRoleId $script:roleId -Dsl $script:dsl
    }
}

    It "Creates a new JumpCloud workflow" {
        $workflowName = "Pester_New_$(Get-Random)"
        $newWorkflow = New-JCWorkflow -Name $workflowName -ExecutionRoleId $script:roleId -Dsl $script:dsl

        $newWorkflow.name | Should -Be $workflowName
        $newWorkflow.execution_role_id | Should -Be $script:roleId

        # Cleanup created resource
        if ($newWorkflow.id) {
            $workflowId = $newWorkflow.id
            try {
                InModuleScope 'JumpCloud' {
                    Invoke-JCApi -Method DELETE -Url "$JCUrlBasePath/api/v2/workflows/$workflowId"
                }
            } catch {
                # Ignore cleanup errors
            }
        }
    }
}