Describe -Tag('JCWorkflow') 'New-JCWorkflow 1.0' {
    BeforeAll {
        Import-Module "$PSScriptRoot/../../../JumpCloud.psd1" -Force
        [void](Connect-JCOnline)

        # Get valid role ID using module internal scope
        $script:roleId = InModuleScope 'JumpCloud' {
            $roles = Invoke-JCApi -Method GET -Url "$JCUrlBasePath/api/v2/roles"
            if ($null -ne $roles.results) { return $roles.results[0].id }
            return $roles[0].id
        }

        # Valid DSL structure generated by official JumpCloud Gemini Gem
        $script:dsl = @{
            schedule = @{
                on = @{
                    one = @{
                        with = @{
                            source = "external"
                        }
                    }
                }
            }
            do = @(
                @{
                    getSystemUsers = @{
                        call = "jc_operation"
                        with = @{
                            operationId = "getApiSystemusers"
                            queryParams = @{
                                limit = 10
                            }
                        }
                    }
                }
            )
        }
    }

    It "Creates a new JumpCloud workflow" {
        $workflowName = "Pester_New_$(Get-Random)"
        $newWorkflow = New-JCWorkflow -Name $workflowName -ExecutionRoleId $script:roleId -Dsl $script:dsl

        $newWorkflow.name | Should -Be $workflowName
        $newWorkflow.execution_role_id | Should -Be $script:roleId

        # Cleanup created resource
        if ($newWorkflow.id) {
            $workflowId = $newWorkflow.id
            try {
                InModuleScope 'JumpCloud' {
                    Invoke-JCApi -Method DELETE -Url "$JCUrlBasePath/api/v2/workflows/$workflowId"
                }
            } catch {
                # Ignore cleanup errors
            }
        }
    }
}